name = "overlay"
version = "1.0.0"

description = "An open LLM workspace assistant."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
castor = ">= 2.0.0 and < 3.0.0"
eyg_interpreter = ">= 1.1.0 and < 2.0.0"
eyg_ir = ">= 1.0.0 and < 2.0.0"
eyg_parser = ">= 0.2.0 and < 1.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glint = ">= 1.2.1 and < 2.0.0"
julienne = ">= 1.1.0 and < 2.0.0"
mork = ">= 1.11.1 and < 2.0.0"
multiformats = ">= 4.0.0 and < 5.0.0"
oas_generator_utils = ">= 1.1.0 and < 2.0.0"
ogre = ">= 1.0.0 and < 2.0.0"
overlay_llm = { path = "../llm" }
touch_grass = ">= 0.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
