name = "overlay_bun"
version = "1.0.0"
target = "javascript"

description = "An open LLM workspace assistant."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
overlay = { path = "../overlay" }
overlay_llm = { path = "../llm" }
simplifile = ">= 2.4.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "bun"
